config/routes.rb
Rails.application.routes.draw do
  get '/apis/news' => 'apis#news'
  resources :urls
  resources :sub_categories
  resources :categories
  resources :bookmarks
  root 'sub_categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
    belongs_to :category
    has_many :urls, as: :urlable

end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
    @url = Url.new
    @urls = Url.all
    @categories = Category.all
    @bookmarks = Bookmark.all
    @sub_cat_chart = SubCategory.group(:name).count
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.js {render layout: false}
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to new_category_path, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :privacy, :category_id)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_with(model: sub_category) do |form| %>
  <% if sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_reference_ID %>
    <%= form.number_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Private %>
    <%= form.check_box :privacy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_categories/_sub_categories_list.html.erb
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Privacy</th>
      <th>Bleongs to </th>
      <th>Category Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.id %></td>
        <td><%= sub_category.name %></td>
        <%if sub_category.privacy?%>
          <td><%= 'Private' %></td>
        <%end%>
        <%if !sub_category.privacy%>
          <td><%= 'Public' %></td>
        <%end%>
        <td><%= sub_category.category.name %></td>
        <td><%= sub_category.category.id %></td>
        <td><%= link_to 'Show', sub_category_path(sub_category) %></td>
        <td><%= link_to 'Edit', edit_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Sub Category Name</th>
      <th>Sub Category Urls</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.name %></td>
        <td><%= url_list(sub_category) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sub_categories/create.js.erb
alert("Your sub category was created successfuly ")
location.reload();

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>
<table>
  <thead>
    <tr>
      <th>Bookmark Name</th>
      <th>Bookmark Categories</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.name %></td>
        <td><%= bookmark_list(bookmark) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>Categories</h1>
<table>
  <thead>
    <tr>
      <th>Category Id</th>
      <th>Category Name</th>
      <th>Sub categories</th>
      <th>Category Urls</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <%if !category.privacy%>
          <td><%= category.id %></td>
          <td><%= category.name %></td>
          <td><%= category_list(category) %></td>
          <td><%= url_list(category) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<h1>Sub-Categories</h1>
<table>
  <thead>
    <tr>
      <th>Sub Category Id</th>
      <th>Sub Category Name</th>
      <th>Sub Category Urls</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <%if !sub_category.privacy%>
          <td><%= sub_category.id %></td>
          <td><%= sub_category.name %></td>
          <td><%= url_list(sub_category) %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<br>
<h2>Add your Urls</h2>
<%= render '/urls/form', url: @url%>
<br>
<hr>
<h2>Admin Bookmarks Managament</h2>
<div> 
  <%= link_to 'Manage Bookmark', new_bookmark_path %>
</div>
<div>
  <%= link_to 'Manage Category', new_category_path %>
</div>
<div>
  <%= link_to 'Manage Sub Category', new_sub_category_path %>
</div>

<hr>

<h2>Sub-Category Distribution</h2>
<%= pie_chart @sub_cat_chart %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= render '/sub_categories/sub_categories_list', sub_category: @sub_category%>

<%= link_to 'Back', root_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_category.name %>
</p>

<p>
  <strong>Privacy:</strong>
  <%= @sub_category.privacy %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', new_sub_category_path %>