config/routes.rb
Rails.application.routes.draw do
  get '/apis/news' => 'apis#news'
  resources :urls
  resources :sub_categories
  resources :categories
  resources :bookmarks
  root 'sub_categories#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :sub_categories, dependent: :destroy
    belongs_to :bookmark
    has_many :urls, as: :urlable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    respond_to do |format|
      format.html
      format.js { render status: :created, location: @category }
    end
    @category = Category.new
    @categories = Category.all
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.js {render layout: false}
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    
    respond_to do |format|
      if @category.update(category_params) && @category.privacy == true
        @sub_categories = SubCategory.where(category_id: @category.id)
        @sub_categories.each do |sub_category|
          sub_category.update(privacy: true)
        end
        format.html { redirect_to new_category_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      elsif @category.update(category_params) && @category.privacy == false
        @sub_categories = SubCategory.where(category_id: @category.id)
        @sub_categories.each do |sub_category|
          sub_category.update(privacy: false)
        end
        format.html { redirect_to new_category_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to new_category_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :privacy, :bookmark_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categorieslist.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Privacy</th>
      <th>Belongs to </th>
      <th>Bookmark Id </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <%if category.privacy?%>
          <td><%= 'Private' %></td>
        <%end%>
        <%if !category.privacy%>
          <td><%= 'Public' %></td>
        <%end%>
        <td><%= category.bookmark.name %></td>
        <td><%= category.bookmark.id %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Sub categories</th>
      <th>Category Urls</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category_list(category) %></td>
        <td><%= url_list(category) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/_form.html.erb
<%= form_with(model: @category) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= form.label :bookmar_reference_ID %>
    <%= form.number_field :bookmark_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Private %>
    <%= form.check_box :privacy %>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/categories/_form2.html.erb
<%= form_with(model: @category) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="field">
    <%= form.label :bookmar_reference_ID %>
    <%= form.text_field :bookmark_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Private %>
    <%= form.check_box :privacy %>
  </div>

  <div class="actions">
    <%= form.submit data: { confirm: 'Changes in pravicy will affect your Sub categories privacy to!' }%>
  </div>
<% end %>

app/views/categories/create.js.erb
alert("Your category was created successfuly ")
location.reload();

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form2', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', new_category_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Privacy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.privacy %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>
<div id="table">
  <%= render '/categories/categorieslist', category: @category%>
</div>

<%= link_to 'Back', root_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Privacy:</strong>
  <%= @category.privacy %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>